name: Deploy to AWS S3
on:
  push:
    branches:
      - staging

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      CI: false # Set CI to false to prevent warnings from being treated as errors

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: NodeJS Setup
        uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: "https://npm.pkg.github.com" # GitHub Packages URL
          scope: "@bmesol" # Replace with your GitHub organization or user scope
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_GITHUB }} # Using GITHUB_TOKEN for GitHub Package

      - name: NPM Install
        run: npm install

      - name: NPM Build
        run: npm run build

      - name: Config AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to AWS S3
        run: aws s3 sync build s3://workinsite-frontend --delete
